import { Product } from "./types";

export const categories = [
  "הכל",
  "אלקטרוניקה",
  "אופנה",
  "בית וגינה",
  "ספורט וחוץ",
  "יופי וטיפוח",
  "ספרים וצעצועים",
] as const;

export const categoryGradients: Record<string, string> = {
  אלקטרוניקה: "from-sky-400 to-blue-600",
  אופנה: "from-pink-400 to-rose-600",
  "בית וגינה": "from-lime-400 to-emerald-600",
  "ספורט וחוץ": "from-orange-400 to-red-500",
  "יופי וטיפוח": "from-fuchsia-400 to-purple-600",
  "ספרים וצעצועים": "from-amber-400 to-yellow-600",
};

export const products: Product[] = [
  {
    id: "p1",
    name: "אוזניות אלחוטיות פרו",
    description: "אוזניות Bluetooth עם ביטול רעשים אקטיבי וסוללה ל-30 שעות.",
    price: 349.9,
    category: "אלקטרוניקה",
    emoji: "🎧",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p2",
    name: "שעון חכם ספורט",
    description: "מעקב דופק, שינה ואימונים, עמיד למים, מסך AMOLED בהיר.",
    price: 599,
    category: "אלקטרוניקה",
    emoji: "⌚",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "p3",
    name: "רמקול נייד עמיד למים",
    description: "סאונד 360 מעלות, חיבור Bluetooth 5.3, סוללה ל-12 שעות.",
    price: 189,
    category: "אלקטרוניקה",
    emoji: "🔊",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "p4",
    name: "מטען אלחוטי מהיר",
    description: "טעינה מהירה 15W התואמת לכל המכשירים התומכים ב-Qi.",
    price: 79.9,
    category: "אלקטרוניקה",
    emoji: "🔌",
    rating: 4.0,
    inStock: false,
  },
  {
    id: "p5",
    name: "חולצת כותנה קלאסית",
    description: "חולצת טי 100% כותנה, גזרה נוחה, מגוון צבעים.",
    price: 89,
    category: "אופנה",
    emoji: "👕",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "p6",
    name: "מכנסי ג'ינס סלים פיט",
    description: "ג'ינס איכותי עם מעט אלסטן לנוחות מרבית.",
    price: 219,
    category: "אופנה",
    emoji: "👖",
    rating: 4.1,
    inStock: true,
  },
  {
    id: "p7",
    name: "מעיל חורף קל משקל",
    description: "בידוד תרמי מתקדם, עמיד למים, קל לקיפול.",
    price: 349,
    category: "אופנה",
    emoji: "🧥",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "p8",
    name: "נעלי ריצה קלות",
    description: "בלימת זעזועים מתקדמת, רשת נושמת, משקל קל.",
    price: 299,
    category: "ספורט וחוץ",
    emoji: "👟",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p9",
    name: "מזרן יוגה אנטי-סליפ",
    description: "עובי 6 מ״מ, ידית נשיאה, ללא ריח, לתרגול נוח.",
    price: 99,
    category: "ספורט וחוץ",
    emoji: "🧘",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "p10",
    name: "בקבוק תרמי לשמירת חום/קור",
    description: "פלדת אל-חלד, שומר חום 12 שעות וקור 24 שעות, 750 מ״ל.",
    price: 69.9,
    category: "ספורט וחוץ",
    emoji: "🥤",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "p11",
    name: "סט סכו״ם למטבח",
    description: "סט 24 חלקים מנירוסטה, עמיד ומבריק, מתאים למדיח כלים.",
    price: 159,
    category: "בית וגינה",
    emoji: "🍴",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "p12",
    name: "נר ריחני בעבודת יד",
    description: "שעות שמן טבעי, ריח לבנדר מרגיע, זמן בעירה 40 שעות.",
    price: 45,
    category: "בית וגינה",
    emoji: "🕯️",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p13",
    name: "עציץ צמח נוי מלאכותי",
    description: "עיצוב ריאליסטי, ללא צורך בהשקיה, מתאים לכל חלל.",
    price: 119,
    category: "בית וגינה",
    emoji: "🪴",
    rating: 4.0,
    inStock: true,
  },
  {
    id: "p14",
    name: "סרום ויטמין C לפנים",
    description: "מבהיר ומחדש, מתאים לכל סוגי העור, 30 מ״ל.",
    price: 129,
    category: "יופי וטיפוח",
    emoji: "🧴",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "p15",
    name: "מברשת פנים חשמלית",
    description: "ניקוי עמוק ועדין, 3 מצבי עוצמה, נטענת ב-USB.",
    price: 149,
    category: "יופי וטיפוח",
    emoji: "🧼",
    rating: 4.1,
    inStock: false,
  },
  {
    id: "p16",
    name: "סט מברשות איפור מקצועי",
    description: "12 מברשות רכות במיוחד עם נרתיק נשיאה.",
    price: 89.9,
    category: "יופי וטיפוח",
    emoji: "💄",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "p17",
    name: "רומן מתח רב מכר",
    description: "כריכה רכה, 320 עמודים, מתורגם לעברית.",
    price: 59,
    category: "ספרים וצעצועים",
    emoji: "📖",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "p18",
    name: "פאזל 1000 חלקים",
    description: "נוף הרים מרהיב, איכות הדפסה גבוהה, לכל הגילאים.",
    price: 74.9,
    category: "ספרים וצעצועים",
    emoji: "🧩",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "p19",
    name: "רכבת צעצוע מעץ",
    description: "עשויה מעץ טבעי בטוח, מפתחת דמיון ומוטוריקה עדינה.",
    price: 99,
    category: "ספרים וצעצועים",
    emoji: "🚂",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "p20",
    name: "מקלדת מכנית RGB",
    description: "מתגים כחולים, תאורה הניתנת להתאמה אישית, USB-C.",
    price: 249,
    category: "אלקטרוניקה",
    emoji: "⌨️",
    rating: 4.5,
    inStock: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
